import { FoodItem } from "@/models/FoodItem";

export const foodFakeArray: FoodItem[] = [
  {
    id: "1",
    title: "Хлеб",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Суббота 14:00 - 18:00",
    location: "ул. Пушкина, д. 7",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "2",
    title: "Tomatoes",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Пятница 15:00 - 19:00",
    location: "ул. Кукушкина, д. 10",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "3",
    title: "Йогурт",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Вторник 8:00 - 18:00",
    location: "ул. Таганская, д. 15",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "4",
    title: "Шоколад",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Воскресенье 10:00 - 20:00",
    location: "ул. Тверская, д. 28",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "5",
    title: "Бананы",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Суббота 16:00 - 18:00",
    location: "ул. Поповича, д. 5",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "6",
    title: "Печеньки",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Понедельник 9:00 - 18:00",
    location: "ул. Ревягина, д. 25",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "7",
    title: "Хлеб",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Суббота 14:00 - 18:00",
    location: "ул. Пушкина, д. 7",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "closed",
  },
  {
    id: "8",
    title: "Tomatoes",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Пятница 15:00 - 19:00",
    location: "ул. Кукушкина, д. 10",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "9",
    title: "Йогурт",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Вторник 8:00 - 18:00",
    location: "ул. Таганская, д. 15",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "reserved",
  },
  {
    id: "10",
    title: "Шоколад",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Воскресенье 10:00 - 20:00",
    location: "ул. Тверская, д. 28",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "closed",
  },
  {
    id: "11",
    title: "Бананы",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Суббота 16:00 - 18:00",
    location: "ул. Поповича, д. 5",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "open",
  },
  {
    id: "12",
    title: "Печеньки",
    author: "Дмитрий Джаваскриптович",
    category: "Мучные изделия",
    description:
      "Хлебушек бородинский, свежий из печи. Недавно испекли, но остался лишний. Всего 3 батона. Заберите пожалуйста его.",
    amount: "3 батона",
    timeCreated: "Пятница 14:00 - 18:00",
    timeToTake: "Понедельник 9:00 - 18:00",
    location: "ул. Ревягина, д. 25",
    phone: "+79031112233",
    imageSrc: "/images/landing_background.jpg",
    status: "reserved",
  },
];
